name: Build docker-image and push to GAR
on:
  workflow_call:
    inputs:
      GCLOUD_ZONE:
        required: true
        type: string
      DOCKERFILE_PATH:
        required: true
        type: string
      GCLOUD_DOCKER_FILE:
        required: true
        type: string
    secrets:
      GCP_CREDENTIALS:
        required: true

# jobs define all steps through which the pipeline goes
jobs:     
  docker-image-buildPush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: GCloud authentification
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Conf Docker to use GAR
        run: gcloud auth configure-docker ${{ inputs.GCLOUD_ZONE }}.pkg.dev

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
        
      - name: Build and Push Docker image with Cache
        run: | 
          docker buildx build \
            --tag ${{ inputs.GCLOUD_DOCKER_FILE }}:test \
            --file ${{ inputs.DOCKERFILE_PATH }} \ # Use the Dockerfile path input
            --cache-from=type=registry,ref=${{ inputs.GCLOUD_DOCKER_FILE }}:latest \ # Attempt to pull cache from latest
            --cache-to=type=inline \ # Embed cache metadata in the pushed image
            --push \
            .
