name: Build docker-image and push to GAR
on:
  workflow_call:
    inputs:
      GCLOUD_ZONE:
        required: true
        type: string
      DOCKERFILE_PATH:
        required: true
        type: string
      GCLOUD_DOCKER_FILE:
        required: true
        type: string
    secrets:
      GCP_CREDENTIALS:
        required: true

jobs:     
  docker-image-buildPush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - name: GCloud authentification
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info
 
      - name: Conf Docker to use GAR
        run: gcloud auth configure-docker ${{ inputs.GCLOUD_ZONE }}.pkg.dev
 
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
 
      - name: Build Docker from cache
        run: | 
          docker buildx build \
            --tag ${{ inputs.GCLOUD_DOCKER_FILE }}:test \
            --cache-from=type=registry,ref=${{ inputs.GCLOUD_DOCKER_FILE }}:cacheout \
            --cache-to=type=registry,ref=${{ inputs.GCLOUD_DOCKER_FILE }}:cachein,mode=max \
            --push \
            --file ${{ inputs.DOCKERFILE_PATH }} .
