name: Build docker-image and push to GAR
on:
  workflow_call:
    inputs:
      GCLOUD_ZONE:
        required: true
        type: string
      DOCKERFILE_PATH:
        required: true
        type: string
      GCLOUD_DOCKER_FILE:
        required: true
        type: string
      GAR_TAG:
        required: true
        type: string
    secrets:
      GCP_CREDENTIALS:
        required: true

jobs:     
  docker-image-buildPush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - name: GCloud authentification
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info
 
      - name: Conf Docker to use GAR
        run: gcloud auth configure-docker ${{ inputs.GCLOUD_ZONE }}.pkg.dev
 
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
 
      - name: Build Docker from cache
        run: | 
          docker buildx build \
            --tag ${{ inputs.GCLOUD_DOCKER_FILE }}:${{ inputs.GAR_TAG }} \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new \
            --push \
            --file ${{ inputs.DOCKERFILE_PATH }} .

      - name: Move new cache for reuse
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
