name: SonarQube Scan

on:
  workflow_call:
    inputs:
      PROJECT_KEY:
        required: true
        type: string
      HOST_URL:
        required: true
        type: string
      SOURCES:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  sonarQubeScan:
    name: SonarQube Scanner
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download Sonar Scanner
        run: |
          set -euo pipefail
          ver="5.0.1.3006"
          url="https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${ver}.zip"
          wget "$url"
          mkdir -p sonar-scanner
          unzip -q "sonar-scanner-cli-${ver}.zip" -d ./sonar-scanner
          chmod +x "./sonar-scanner/sonar-scanner-${ver}/bin/sonar-scanner"

      - name: Run SonarQube Scan and wait for Quality Gate
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          set -euo pipefail
          ./sonar-scanner/sonar-scanner-5.0.1.3006/bin/sonar-scanner \
            -Dsonar.projectKey=${{ inputs.PROJECT_KEY }} \
            -Dsonar.sources=${{ inputs.SOURCES }} \
            -Dsonar.host.url=${{ inputs.HOST_URL }} \
            -Dsonar.token=${SONAR_TOKEN} \
            -Dsonar.qualitygate.wait=true
