name: Reusable SonarQube Scan

on:
  workflow_call:
    inputs:
      projectKey:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true

jobs:
  sonarQubeScan:
    name: SonarQube Scanner
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run SonarQube Scan and wait for Quality Gate
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006.zip
          mkdir sonar-scanner
          unzip sonar-scanner-cli-5.0.1.3006.zip -d ./sonar-scanner
          chmod +x ./sonar-scanner/sonar-scanner-5.0.1.3006/bin/sonar-scanner
          ./sonar-scanner/sonar-scanner-5.0.1.3006/bin/sonar-scanner \
            -Dsonar.projectKey=${{ inputs.projectKey }} \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.qualitygate.wait=true
