name: Terraform template

on:
  workflow_call:
    inputs:
     DIR_PATH:
       required: true
       type: string
     IMPORT:
       required: true
       type: boolean
     PROJECT_NAME:
       required: true
       type: string
      

jobs:
  terraform:
    name: "Terraform deploy"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.DIR_PATH }}

    steps:
      - uses: actions/checkout@v3

      - name: GCloud authentification
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.3
        
      - name: Terraform Init
        run: terraform init

      - name: Import firewall
        if: ${{ inputs.IMPORT == true }}
        run: | 
             terraform import google_compute_firewall.allow_http_https projects/${{ inputs.PROJECT_NAME }}/global/firewalls/allow-http-https
             terraform import google_compute_address.static_ip projects/${{ inputs.PROJECT_NAME }}/regions/europe-west2/addresses/vm-static-ip

      - name: Turn on all needed apis
        run: terraform apply -target=google_project_service.apis -auto-approve

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
