name: Terraform template

on:
  workflow_call:
    inputs:
      DIR_PATH:
        required: true
        type: string
      IMPORT:
        required: true
        type: boolean
      PROJECT_ID:
        required: true
        type: string
      REGION:
        required: false
        type: string
      VPC_NAME:
        required: false
        type: string
      SUBNET_NAME:
        required: false
        type: string
      SUBNET_IP_RANGE:
        required: false
        type: string
      DB_VERSION:
        required: false
        type: string
      DB_INSTANCE_NAME:
        required: false
        type: string
      DB_USER:
        required: false
        type: string
      DB_PASSWORD:
        required: false
        type: string
      DB_NAME:
        required: false
        type: string
      DB_TIER:
        required: false
        type: string
      ZONE:
        required: false
        type: string
      VM_NAME:
        required: false
        type: string
      MACHINE_TYPE:
        required: false
        type: string
      SERVICE_ACCOUNT_ID:
        required: false
        type: string
      ROLES:
        required: false
        type: string
      REPO_ID:
        required: false
        type: string
      BUCKET_NAME:
        required: false
        type: string
      STORAGE_CLASS:
        required: false
        type: string
      ENABLE_VERSION:
        required: false
        type: string

jobs:
  terraform:
    name: "Terraform deploy"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.DIR_PATH }}

    steps:
      - uses: actions/checkout@v3

      - name: GCloud authentification
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.3
        
      - name: Terraform Init
        run: terraform init

      - name: Turn on all needed apis
        run: terraform apply -target=google_project_service.apis -auto-approve

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
